collections:
  authors:
    output: true

defaults:
- scope:
    path: ""
    type: "authors"
  values:
    layout: "author"
- scope:
    path: ""
    type: "posts"
  values:
    layout: "post"
- scope:
    path: ""
  values:
    layout: "default"

plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman